version: '2'

services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
      - "50000:50000"
    links: 
      - jenkins:myjenkins  
    volumes:
      - /home/ddot/nginx/conf:/etc/nginx/conf.d
      - /home/ddot/nginx/www:/www
    networks:
      - front 
      - back

  jenkins:
    image: jenkins:alpine
    volumes:
      - /home/ddot/jenkins_home:/var/jenkins_home
      - /home/ddot/nginx/www:/www
    expose:
      - "8080"
      - "50000" 
    networks:
      - back  

networks:
  front:
    driver: bridge
  back:
    driver: bridge