version: '2'

services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - /home/ddot/nginx:/etc/nginx/conf.d
    environment:
      - NGINX_HOST=dot.com 
    networks:
      - front
      - back

  jenkins:
    image: jenkins:alpine
    volumes:
      - /home/ddot/jenkins_home:/var/jenkins_home
    expose:
      - "8080"
      - "50000" 
    networks:
      - back  

networks:
  front:
    driver: bridge
  back:
    driver: bridge