version: '2'

services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
      - "4873:4873"
    links: 
      - jenkins:myjenkins  
      - verdaccio:mysinopia
    volumes:
      - /home/ddot/nginx/conf:/etc/nginx/conf.d
      - /home/ddot/nginx/cert:/etc/nginx/cert
      - /home/ddot/nginx/www:/www
    networks:
      - front 
      - back

  jenkins:
    image: jenkinsnode:7
    volumes:
      - /home/ddot/jenkins_home:/var/jenkins_home
      - /home/ddot/nginx/www:/www
    links: 
      - verdaccio:mysinopia  
    expose:
      - "8080"
      - "50000" 
    networks:
      - back  

  verdaccio:
    image: verdaccio/verdaccio
    volumes:
      - /home/ddot/verdaccio/config.yaml:/verdaccio/conf/config.yaml
      - /home/ddot/verdaccio/htpasswd:/verdaccio/conf/htpasswd
    expose:
      - "4873" 
    networks:
      - back  

networks:
  front:
    driver: bridge
  back:
    driver: bridge