version: '3.7'

services:
  web:
    image: nginx:1.14.2-alpine
    ports:
      - "80:80"
      - "443:443"
    restart: always
    links: 
      - ghost
    volumes:
      - /usr/me/nginx/conf:/etc/nginx/conf.d
      - /usr/me/nginx/cert:/etc/nginx/cert
    container_name: nginx-host
    networks:
      - front

  ghost:
    image: ghost:2.14.3-alpine
    restart: always
    container_name: ghost
    environment:
      - NODE_ENV:production
    networks:
      - front

networks:
  front: